name: 'PR to Discord'
author: 'Munbin-Lee'
description: 'sends PR notifications to Discord.'
branding:
  icon: 'award'
  color: 'blue'

inputs:
  discord_webhook_url:
    description: 'webhook URL of a Discord channel.'
    required: true
  pull_request:
    description: 'Pull request json.'
    required: false
    default: ${{ toJson(github.event.pull_request) }}

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: >
        PROBLEM=$(
          echo ${{ toJson(inputs.pull_request.body) }} |
          grep -Pio 'http[\w\:\/\.-]+' |
          head -1
        );
        echo "PROBLEM=$PROBLEM" >> $GITHUB_ENV
    - shell: bash
      env:
        DATA: >
          {
            "username": ${{ toJson(fromJson(inputs.pull_request).user.login) }},
            "avatar_url": ${{ toJson(fromJson(inputs.pull_request).user.avatar_url) }},
            "embeds": [
              {
                "title": ${{ toJson(fromJson(inputs.pull_request).title) }},
                "description": "새로운 PR이 도착했습니다!\n\n${{ env.PROBLEM }}",
                "url": ${{ toJson(fromJson(inputs.pull_request).html_url) }},
                "color": 6847432
              }
            ]
          }
      run: >
        curl -X
        POST -H 'Content-type:application/json'
        -d "$DATA"
        ${{ inputs.discord_webhook_url }}
